### PR TITLE
Create 20221231 BioArchLinux.md

### PR DESCRIPTION
**Pull request by starsareintherose**

### CODE REVIEW

**Comment by lin-calvin** [comment]
you may try to mention @wxy in linux.cn's offical wechat group chat?

**Comment by starsareintherose** [comment]
How can I join the wechat group?

**Comment by calvinweb** [comment]
> How can I join the wechat group?

by this qrcode

**Comment by lin-calvin** [comment]
> How can I join the wechat group?
by this
mmexport1672578394060

**Review by wxy — APPROVED** [review]

**Pull request merged**
